module.exports = {
	sightWords: {
    grade1: {
      'after': 'after',
      'again': 'again',
      'an': 'an',
      'any': 'any',
      'as': 'as',
      'ask': 'ask',
      'by': 'by',
      'could': 'could',
      'every': 'every',
      'fly': 'fly',
      'from': 'from',
      'give': 'give',
      'going': 'going',
      'had': 'had',
      'has': 'has',
      'her': 'her',
      'hers': 'hers',
      'him': 'him',
      'his': 'his',
      'how': 'how',
      'just': 'just',
      'know': 'know',
      'let': 'let',
      'live': 'live',
      'may': 'may',
      'of': 'of',
      'old': 'old',
      'once': 'once',
      'open': 'open',
      'over': 'over',
      'put': 'put',
      'round': 'round',
      'some': 'some',
      'stop': 'stop',
      'take': 'take',
      'thank': 'thank',
      'them': 'them',
      'then': 'then',
      'think': 'think',
      'walk': 'walk',
      'were': 'were',
      'when': 'when'
    }
  }
}
